language: node_js
node_js:
  - "4.2"
  - "5.5"
cache:
  directories:
    - node_modules
    - .nvm
install: npm install
script: npm run coverage
after_script: npm run coveralls
notifications:
  email:
    on_success: never
    on_failure: change
